# Generated by Django 5.2.15 on 2026-08-27 17:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, unique=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('client', 'Client'), ('fournisseur', 'Fournisseur'), ('mixte', 'Mixte')], max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Togo', max_length=100)),
                ('conditions_paiement', models.CharField(blank=True, max_length=255)),
                ('nom', models.CharField(max_length=150)),
                ('fonction', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('principal', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('unite', models.CharField(choices=[('pce', 'pce'), ('m', 'm'), ('kit', 'kit'), ('lot', 'lot')], default='pce', max_length=10)),
                ('origine', models.CharField(blank=True, max_length=100)),
                ('code_douanier', models.CharField(blank=True, max_length=50)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taux_majoration', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('qte_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('emplacement', models.CharField(blank=True, max_length=120)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Cotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=120, unique=True)),
                ('indice', models.PositiveIntegerField(default=1)),
                ('date_cot', models.DateField(default=django.utils.timezone.now)),
                ('objet', models.CharField(blank=True, max_length=255)),
                ('devis_festo', models.CharField(blank=True, max_length=120)),
                ('poids_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux_majoration', models.DecimalField(decimal_places=3, default=0.3, max_digits=6)),
                ('taux_douane', models.DecimalField(decimal_places=3, default=0.075, max_digits=6)),
                ('taux_change', models.DecimalField(decimal_places=3, default=655.957, max_digits=12)),
                ('montant_marchandises', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transport', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('douane', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cout_achat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_validite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('relancee', 'Relancée'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('expiree', 'Expirée')], default='brouillon', max_length=20)),
                ('date_envoi', models.DateField(blank=True, null=True)),
                ('date_relance_14', models.DateField(blank=True, null=True)),
                ('date_relance_30', models.DateField(blank=True, null=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tiers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotations', to='core.tiers')),
            ],
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé')], default='brouillon', max_length=20)),
                ('signataire', models.CharField(blank=True, max_length=150)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison', to='core.cotation')),
                ('tiers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tiers')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_fac', models.DateField(default=django.utils.timezone.now)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taux_tva', models.DecimalField(decimal_places=3, default=0.18, max_digits=5)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_regle', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('statut', models.CharField(choices=[('emise', 'Émise'), ('partiellement_reglee', 'Partiellement réglée'), ('reglee', 'Réglée'), ('en_retard', 'En retard'), ('annulee', 'Annulée')], default='emise', max_length=30)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='core.cotation')),
                ('tiers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='core.tiers')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=80)),
                ('objet', models.CharField(max_length=100)),
                ('objet_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_majoration', models.DecimalField(decimal_places=3, max_digits=6)),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.article')),
                ('cotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.cotation')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.article')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.facture')),
            ],
        ),
        migrations.CreateModel(
            name='LigneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.article')),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.bonlivraison')),
            ],
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.CharField(max_length=255)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commentaire', models.CharField(blank=True, default='', max_length=255)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode', models.CharField(default='Espèces', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='core.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_mvt', models.DateTimeField(default=django.utils.timezone.now)),
                ('motif', models.TextField(blank=True)),
                ('doc_type', models.CharField(blank=True, choices=[('bon_livraison', 'Bon de livraison'), ('achat', 'Achat'), ('inventaire', 'Inventaire')], max_length=30)),
                ('doc_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='core.article')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tiers')),
            ],
        ),
        migrations.CreateModel(
            name='UtilisateurProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.CharField(choices=[('direction', 'Direction'), ('commercial', "Chargé d'affaires"), ('magasinier', 'Magasinier'), ('consultation', 'Consultation')], default='consultation', max_length=30)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
